// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkjaktntksksquimsuhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpramFrdG50a3Nrc3F1aW1zdWhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMDE4ODUsImV4cCI6MjA2MDc3Nzg4NX0.5ja5PaRKZa1nLoCg36kvB22LUwzuGuLETEeMvH4Bnf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);